inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.4

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Metrics/AbcSize:
  Max: 33

Metrics/MethodLength:
  Max: 25

RSpec/NestedGroups:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

Security/Eval:
  Exclude:
    - "Gemfile"
    - "gemfiles/*.gemfile"
