inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.1

RSpec/NestedGroups:
  Enabled: false

Metrics/AbcSize:
  Max: 33

Metrics/MethodLength:
  Max: 25

Security/Eval:
  Exclude:
    - "Gemfile"
    - "gemfiles/*.gemfile"
