inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: disable

Layout/ClassStructure:
  Enabled: false

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle:      table

Metrics/AbcSize:
  Max: 37

Metrics/MethodLength:
  Max: 25

RSpec/NestedGroups:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/SharedExamples:
  Enabled: false

Security/Eval:
  Exclude:
    - "Gemfile"
    - "gemfiles/*.gemfile"

Style/ExplicitBlockArgument:
  Enabled: false
