language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
gemfile:
  - gemfiles/activerecord_5_0.gemfile
  - gemfiles/activerecord_5_1.gemfile
  - gemfiles/activerecord_5_2.gemfile
  - gemfiles/activerecord_6_0.gemfile
services:
  - mysql
addons:
  # Rails 6.0 requires PostgreSQL 9.3+
  postgresql: "9.3"
env:
  - DATABASE=mysql
  - DATABASE=postgresql
  - DATABASE=sqlite3
bundler_args: --without oracle
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - travis_retry gem install bundler --no-document || travis_retry gem install bundler --no-document -v 1.17.3
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - export CC_TEST_REPORTER_ID=377596024a4c6f3c4c4b9a0cd16add92fb5e7f716663629b5efd080377c0b838
script: "./ci/build.sh"
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
    - master
notifications:
  email: false
  slack:
    secure: YGQKOd0oz96gfQtyfTLj7N2Riq93oj1lR9X5hf4071Zu9q3wQjLD4a5y39iVAtOpK2Lw3ShM93kcGREZfpThx9jQ0jUd26DWLLFokZvM82l5+hD7PMhLU1Pv/EbW7mTGAw1TR0su98m91A71qJghdZsT/UrP+QN/4zV72I8XiYrkAiKaTLaucEN4Pn2GgSAGV4Hs7eqT7jNBkGbxSOio3MttoYMDz7dBfR3Z8GRk7jSL5z820zejHNPbfbpwZQhtx/rY/KGSHoIRDc7je6Aiebd5wElQFKsh13LFYSbGaYvB2gRdU/ZmyG0YLV+0hUvWYS14QvCUFrCbiKmRf58tTk3Y/FVtBga+Aj11JrAgpvR9qf2y+gC3BwBwBwaElZ2gMmfZOzXPI7P+OATKbVCQOE4PCAIUkfBbaYkg6FJlYwaume5n+ObLhZPZwa8EGaOkrzonKRhU7hMBT6A+aQkwz0wfccErEog8vB/5OYSMquxZtfWywLgUpnyg97SYeC8aaON+/U8edWsYUR+0bBIySNYEAq0algQEo52cLh4qNpLJeb/zRdFX2b+CI1EYPa+rDSygD7NpT+mx5/5leAcxyvp4S3iKxjFEVkoKwIEoLnqbqjarwz2LjJ+l32wZDhmBV5UggpKoieV5KtpkIwOCJ4g6t+aq786oSW+/GWWI9s0=
matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    # Rails 6.0 requires Ruby 2.5+
    - rvm:     2.3
      gemfile: gemfiles/activerecord_6_0.gemfile
    - rvm:     2.4
      gemfile: gemfiles/activerecord_6_0.gemfile
cache: bundler
sudo: false
dist: xenial
