version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile

environment: &environment
  LANG:     en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL:   C.UTF-8

  BUNDLE_PATH: vendor/bundle
  CC_TEST_REPORTER_ID: 377596024a4c6f3c4c4b9a0cd16add92fb5e7f716663629b5efd080377c0b838

executors:
  ruby:
    docker:
      - image: circleci/ruby
        environment:
          <<: *environment

    working_directory: /home/circleci/app

  oracle:
    docker:
      - image: deepdiver/docker-oracle-xe-11g
        environment:
          <<: *environment
          DATABASE: oracle
          ORACLE_SYSTEM_PASSWORD: oracle
          NLS_LANG: AMERICAN_AMERICA.UTF8

    working_directory: /home/circleci/app

commands:
  with-cc-test-reporter:
    description: "Run test with cc-test-reporter"
    parameters:
      steps:
        type: steps
        default: []
        description: "Run steps between `before-build` and `after-build`"
    steps:
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - steps: << parameters.steps >>
      - run:
          command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?
          when: always

jobs:
  oracle_activerecord:
    parameters:
      gemfile:
        type: string
    executor:
      name: oracle
    environment:
      BUNDLE_GEMFILE: gemfiles/<< parameters.gemfile >>.gemfile
    steps:
      - run:
          name: Setup ruby
          command: |
            apt-get update
            apt-get install -y software-properties-common
            apt-add-repository -y ppa:brightbox/ruby-ng
            apt-get update
            apt-get install -y ruby2.5 ruby2.5-dev git build-essential tar curl

            gem update --system --no-document
            gem install bundler --no-document
          shell: /bin/bash -xe

      - run:
          name: Setup oracle
          command: |
            export LD_LIBRARY_PATH=$ORACLE_HOME/lib

            # https://github.com/DeepDiver1975/docker-oracle-xe-11g/blob/2ebd4ebca56ea9833ded912612abfbc22914a64a/Dockerfile#L53-L54
            sed -i -E "s/HOST = [^)]+/HOST = $HOSTNAME/g" /u01/app/oracle/product/11.2.0/xe/network/admin/listener.ora
            service oracle-xe start

            /etc/init.d/oracle-xe status
          shell: /bin/bash -xe

      - checkout

      - ruby-orbs/bundle-install:
          with_gemfile_lock: false
          gemspec_name:      "index_shotgun"
          cache_key_prefix:  "v3-bundle"
          bundle_gemfile:    "gemfiles/<< parameters.gemfile >>.gemfile"
          bundle_path:       "gemfiles/vendor/bundle"
          bundle_extra_args: "--without mysql postgresql sqlite3"

      - with-cc-test-reporter:
          steps:
            - run: ./ci/build.sh

  rubocop:
    executor:
      name: ruby

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          with_gemfile_lock: false
          gemspec_name:      "index_shotgun"
          cache_key_prefix:  "v3-bundle"
          bundle_gemfile:    "Gemfile"
          bundle_path:       "vendor/bundle"
          bundle_extra_args: "--without mysql postgresql sqlite3 oracle"

      - run: bundle exec rubocop

build_jobs: &build_jobs
  - oracle_activerecord:
      name:    "oracle_activerecord:5.0"
      gemfile: "activerecord_5_0"
  - oracle_activerecord:
      name:    "oracle_activerecord:5.1"
      gemfile: "activerecord_5_1"
  - oracle_activerecord:
      name:    "oracle_activerecord:5.2"
      gemfile: "activerecord_5_2"
  - rubocop

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
