version: 2.1

environment: &environment
  LANG:     en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL:   C.UTF-8

  BUNDLE_PATH: vendor/bundle
  CODECLIMATE_REPO_TOKEN: 377596024a4c6f3c4c4b9a0cd16add92fb5e7f716663629b5efd080377c0b838

executors:
  ruby:
    docker:
      - image: circleci/ruby:2.1
        environment:
          <<: *environment

    working_directory: /home/circleci/app

  oracle:
    docker:
      - image: wnameless/oracle-xe-11g:16.04
        environment:
          <<: *environment
          DATABASE: oracle

          ORACLE_HOME: /u01/app/oracle/product/11.2.0/xe
          ORACLE_SID: XE
          ORACLE_SYSTEM_PASSWORD: oracle
          NLS_LANG: AMERICAN_AMERICA.UTF8

    working_directory: /home/circleci/app

commands:
  setup_bundle:
    description: "Setup bundle with cache"

    parameters:
      bundle_without:
        type: string

    steps:
      - restore_cache:
          keys:
            - v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
            - v3-bundle-{{ .Environment.CIRCLE_JOB }}

      - run:
          name: Setup
          command: |
            set -xe
            gem install bundler --no-document

            ruby --version
            bundle --version
            gem --version

            bundle check || bundle install --jobs=4 --without << parameters.bundle_without >> --path=${BUNDLE_PATH:-vendor/bundle}
            bundle clean

      - save_cache:
          key: v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - /home/circleci/app/vendor/bundle
            - /home/circleci/app/gemfiles/vendor/bundle
            - /home/circleci/app/Gemfile.lock

jobs:
  oracle_activerecord:
    parameters:
      gemfile:
        type: string
    executor:
      name: oracle
    environment:
      BUNDLE_GEMFILE: gemfiles/<< parameters.gemfile >>.gemfile
    steps:
      - run:
          name: Setup oracle
          command: |
            export PATH=$ORACLE_HOME/bin:$PATH
            export LD_LIBRARY_PATH=$ORACLE_HOME/lib
            apt-get update
            apt-get install -y ruby2.3 ruby2.3-dev git build-essential tar
            /usr/sbin/startup.sh
            /etc/init.d/oracle-xe status
          shell: /bin/bash -xe

      - checkout
      - setup_bundle:
          bundle_without: mysql postgresql sqlite3

      - run: ./ci/build.sh

  rubocop:
    executor:
      name: ruby

    steps:
      - checkout
      - setup_bundle:
          bundle_without: mysql postgresql sqlite3 oracle

      - run: bundle exec rubocop

build_jobs: &build_jobs
  - oracle_activerecord:
      name:    "oracle_activerecord:4.2"
      gemfile: "activerecord_4_2"
  - oracle_activerecord:
      name:    "oracle_activerecord:5.0"
      gemfile: "activerecord_5_0"
  - oracle_activerecord:
      name:    "oracle_activerecord:5.1"
      gemfile: "activerecord_5_1"
  - oracle_activerecord:
      name:    "oracle_activerecord:5.2"
      gemfile: "activerecord_5_2"
  - rubocop

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
