# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

environment: &environment
  LANG:     en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_ALL:   C.UTF-8

  BUNDLE_PATH: vendor/bundle
  BUNDLE_JOBS: 4
  CODECLIMATE_REPO_TOKEN: 377596024a4c6f3c4c4b9a0cd16add92fb5e7f716663629b5efd080377c0b838

default: &default
  docker:
    - image: circleci/ruby:2.1
      environment:
        <<: *environment
        BUNDLE_WITHOUT: mysql postgresql sqlite3 oracle

  working_directory: /home/circleci/app

oracle: &oracle
  docker:
    - image: wnameless/oracle-xe-11g:16.04
      environment:
        <<: *environment
        BUNDLE_WITHOUT: mysql postgresql sqlite3
        DATABASE: oracle

        ORACLE_HOME: /u01/app/oracle/product/11.2.0/xe
        ORACLE_SID: XE
        ORACLE_SYSTEM_PASSWORD: oracle
        NLS_LANG: AMERICAN_AMERICA.UTF8

  working_directory: /home/circleci/app

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
    - v3-bundle-{{ .Environment.CIRCLE_JOB }}

save_bundle_cache_option: &save_bundle_cache_option
  key: v3-bundle-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
  paths:
    - /home/circleci/app/vendor/bundle
    - /home/circleci/app/gemfiles/vendor/bundle
    - /home/circleci/app/Gemfile.lock

rspec_steps: &rspec_steps
  - run:
      name: Setup oracle
      command: |
        export PATH=$ORACLE_HOME/bin:$PATH
        export LD_LIBRARY_PATH=$ORACLE_HOME/lib
        apt-get update
        apt-get install -y ruby2.3 ruby2.3-dev git build-essential tar
        /usr/sbin/startup.sh
        /etc/init.d/oracle-xe status
      shell: /bin/bash -xe

  - checkout
  - restore_cache:
      <<: *restore_bundle_cache_option
  - run: ./.circleci/setup.sh
  - save_cache:
      <<: *save_bundle_cache_option

  - run: ./ci/build.sh

build_jobs: &build_jobs
  - oracle:activerecord:4.2
  - oracle:activerecord:5.0
  - oracle:activerecord:5.1
  - oracle:activerecord:5.2
  - rubocop

jobs:
  oracle:activerecord:4.2:
    <<: *oracle

    environment:
      BUNDLE_GEMFILE: gemfiles/activerecord_4_2.gemfile

    steps: *rspec_steps

  oracle:activerecord:5.0:
    <<: *oracle

    environment:
      BUNDLE_GEMFILE: gemfiles/activerecord_5_0.gemfile

    steps: *rspec_steps

  oracle:activerecord:5.1:
    <<: *oracle

    environment:
      BUNDLE_GEMFILE: gemfiles/activerecord_5_1.gemfile

    steps: *rspec_steps

  oracle:activerecord:5.2:
    <<: *oracle

    environment:
      BUNDLE_GEMFILE: gemfiles/activerecord_5_2.gemfile

    steps: *rspec_steps

  rubocop:
    <<: *default

    steps:
      - checkout
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup.sh
      - save_cache:
          <<: *save_bundle_cache_option

      - run: bundle exec rubocop

workflows:
  version: 2

  build:
    jobs: *build_jobs

  weekly_build:
    triggers:
      - schedule:
          cron: "00 19 * * 5" # JST 4:00 (Sat)
          filters:
            branches:
              only: master
    jobs: *build_jobs
