name: Build

on:
  push:
  schedule:
    - cron: "0 20 * * 5" # JST 5:00 (Sat)

env:
  CI: "true"
  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

jobs:
  matrix:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - v2.4.x
          - v2.5.x
          - v2.6.x
        gemfile:
          - activerecord_5_0.gemfile
          - activerecord_5_1.gemfile
          - activerecord_5_2.gemfile
          - activerecord_6_0.gemfile
        database:
          - sqlite3
          - mysql
          - postgresql
          - oracle
        exclude:
          # Rails 6.0 requires Ruby 2.5+
          - ruby:    v2.3.x
            gemfile: activerecord_6_0.gemfile
          - ruby:    v2.4.x
            gemfile: activerecord_6_0.gemfile

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
      DATABASE: ${{ matrix.database }}
      LD_LIBRARY_PATH: /opt/oracle/instantclient_19_3
      NLS_LANG: AMERICAN_AMERICA.UTF8
      ORACLE_SYSTEM_PASSWORD: oracle

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
        env:
          MYSQL_ROOT_PASSWORD: root
      postgresql:
        image: postgres:10-alpine
        ports:
          - 5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      oracle:
        image: deepdiver/docker-oracle-xe-11g
        ports:
          - 1521
        env:
          ORACLE_SYSTEM_PASSWORD: oracle

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Install
        run: |
          set -xe
          ./ci/install.sh

      - name: setup cc-test-reporter
        run: |
          set -xe
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Run test
        run: |
          set -xe
          ./ci/build.sh
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports['3306'] }}
          POSTGRESQL_PORT: ${{ job.services.postgresql.ports['5432'] }}
          ORACLE_PORT: ${{ job.services.oracle.ports['1521'] }}

      - name: teardown cc-test-reporter
        run: |
          ./cc-test-reporter after-build --exit-code $?
        if: always()

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@v2.0.0
        if: "! success()"
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  rubocop:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: v2.4.x

      - name: Install
        run: |
          set -xe
          ./ci/install.sh

      - name: Run rubocop
        run: |
          set -xe
          bundle exec rubocop

      - name: Slack Notification (not success)
        uses: homoluctus/slatify@v2.0.0
        if: "! success()"
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}

  notify:
    needs:
      - matrix
      - rubocop

    runs-on: ubuntu-latest

    steps:
      - name: Slack Notification (success)
        uses: homoluctus/slatify@v2.0.0
        if: always()
        with:
          job_name: '*build*'
          type: ${{ job.status }}
          icon_emoji: ":octocat:"
          url: ${{ secrets.SLACK_WEBHOOK }}
          token: ${{ secrets.GITHUB_TOKEN }}
