name: Publish gem to rubygems.org

on:
  workflow_dispatch:

jobs:
  release:
    uses: sue445/workflows/.github/workflows/release_gem.yml@main
    with:
      repo-name:      sue445/index_shotgun
      gem-name:       index_shotgun
      bundle-without: mysql:postgresql:sqlite3:oracle
    permissions:
      contents: write
      id-token: write
